export const TOOLBOX_ITEMS = [
  { type: 'text', label: 'Text Input', category: 'Basic Fields' },
  { type: 'textarea', label: 'Long Text', category: 'Basic Fields' },
  { type: 'number', label: 'Number', category: 'Basic Fields' },
  { type: 'email', label: 'Email', category: 'Basic Fields' },
  { type: 'phone', label: 'Phone Number', category: 'Basic Fields' },
  { type: 'date', label: 'Date Picker', category: 'Basic Fields' },
  { type: 'time', label: 'Time Picker', category: 'Basic Fields' },
  { type: 'year', label: 'Year (YYYY)', category: 'Basic Fields' },
  { type: 'gender', label: 'Gender', category: 'Basic Fields' },
  { type: 'checkbox', label: 'Single Checkbox', category: 'Basic Fields' },
  { type: 'dropdown', label: 'Dropdown / Select', category: 'Choices' },
  { type: 'searchable_dropdown', label: 'Searchable Dropdown', category: 'Choices' },
  { type: 'radio', label: 'Radio Buttons', category: 'Choices' },
  { type: 'multi_select', label: 'Multi-select Checkboxes', category: 'Choices' },
  { type: 'searchable_multi_select', label: 'Searchable Multi-select', category: 'Choices' },
  { type: 'rating', label: 'Rating (1-5)', category: 'Choices' },
  { type: 'scale', label: 'Linear Scale (1-10)', category: 'Choices' },
  { type: 'file', label: 'File Upload', category: 'Media' },
  { type: 'image', label: 'Image Upload', category: 'Media' },
  { type: 'signature', label: 'Signature', category: 'Advanced' },
  { type: 'qr_scanner', label: 'QR Scanner', category: 'Advanced' },
  { type: 'gps', label: 'GPS Location', category: 'Advanced' },
  { type: 'cohort_input', label: 'Cohort ID Input', category: 'Advanced' },
  { type: 'dob_age', label: 'DOB & Age', category: 'Health' },
  { type: 'bmi', label: 'BMI Calculator', category: 'Health' },
  { type: 'calculated_score', label: 'Calculated Score', category: 'Health' },
  { type: 'section_header', label: 'Section Header', category: 'Layout' },
  { type: 'instruction', label: 'Instruction Text', category: 'Layout' },
  { type: 'divider', label: 'Divider Line', category: 'Layout' },
  { type: 'page_break', label: 'Page Break', category: 'Layout' }
];
